- name: Generate random strings to use for minio secret_key and minio access_key
  set_fact:
    access_key: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=12') }}"
    secret_key: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=12') }}"

- name: Generate Secrets with Vault
  shell: vault kv put secret/minio access_key="{{ access_key }}" secret_key="{{ secret_key }}"
  run_once: true
  environment:
    VAULT_ADDR: "{{ lookup('env', 'VAULT_ADDR') }}"
    VAULT_TOKEN: "{{ lookup('env', 'vault_master_token') }}"
