- name: Generate Secrets with Vault
  shell: |
    vault kv put secret/minio \
    accessKey=$(vault write -field='value' gen/password length=12 symbols=0) \
    secretKey=$(vault write -field='value' gen/password length=12 symbols=0)
  run_once: true
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"

- name: Register access key
  shell:
    cmd: vault kv get -field='accessKey' secret/minio
  register: access_key

- name: Register secret key
  shell:
    cmd: vault kv get -field='secretKey' secret/minio
  register: secret_key

- name: Delete /etc/default/terraform.tfvars if it exists
  file:
    path: /etc/default/terraform.tfvars
    state: absent

- name: Add access_key and secret_key to the /etc/default/terraform.tfvars file
  shell: |
    echo access_key='"{{ access_key.stdout }}"' >> /etc/default/terraform.tfvars
    echo secret_key='"{{ secret_key.stdout }}"' >> /etc/default/terraform.tfvars
  run_once: true
