- name: Generate Secrets with Vault
  shell: |
    vault kv put secret/minio \
    access_key=$(vault write -field='value' gen/password length=12 symbols=0) \
    secret_key=$(vault write -field='value' gen/password length=12 symbols=0)
  run_once: true
  environment:
    VAULT_ADDR: "{{ lookup('env', 'VAULT_ADDR') }}"
